spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/malikdiopp
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Crud

server:
  port: 8080